# Generated by Django 4.2.1 on 2023-05-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms_api', '0002_employee_remove_ticket_status_ticket_resolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms_api.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms_api.ticket')),
            ],
        ),
    ]
